# Generated by Django 5.2.16 on 2026-09-17 11:17

from django.db import migrations, models


def align_steam_records(apps, schema_editor):
    Game = apps.get_model('app', 'Game')
    History = apps.get_model('app', 'HistoricalGame')
    Link = apps.get_model('app', 'LibraryLink')
    database = schema_editor.connection.alias
    games = Game.objects.using(database).filter(item__source='steam')
    created = History.objects.using(database).filter(history_type='+').values('id')
    edited = History.objects.using(database).exclude(history_type='+').values('id')
    games.filter(
        pk__in=created, status='Paused', progress__gt=0,
        score__isnull=True, notes='', start_date__isnull=True, end_date__isnull=True,
    ).exclude(pk__in=edited).update(status='In progress')
    for game in games.select_related('item').iterator():
        Link.objects.using(database).get_or_create(
            user_id=game.user_id,
            item_id=game.item_id,
            defaults={'url': f'https://store.steampowered.com/app/{game.item.media_id}/'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_library_import_drafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.RunPython(align_steam_records, migrations.RunPython.noop),
    ]
