# Generated by Django 5.2.16 on 2026-09-26 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_library_folders_and_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='librarylink',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='LibraryRecommendationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('media_type', models.CharField(max_length=20)),
                ('media_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'media_type', 'media_id'), name='library_dismissal_owner_work')],
            },
        ),
    ]
